### ISSUE TITLE
Invisible mobs when world loaded first w/o mod

### ISSUE THREAD

**Issue by WenXin20** [Epoxide-MC/Colorful-Mobs#2]
When the mod is added after the world is already created, the mobs turn invisible.

**Comment by Darkhax** [comment]
Can you please add some more information?. During a test, we could not reproduce this issue. Does this happen with all mobs, or just dyed ones?

**Comment by WenXin20** [comment]
All Mobs. If the mod is not installed when I create a world the mobs are vsible, then when I add the mod, the mobs turn invisible.  If I find the invisible mob, the color wand tells me the colors are set to 0 0 0, with invisibility at 100%.

**Comment by Darkhax** [comment]
I have been able to reproduce the issue. One of the recent changes in the code fixed this issue to a degree, rather than being invisible, mobs are shown as having no colors. I am still working to find where this issue exactly is within the code.

**Comment by Darkhax** [comment]
The issue has been solved, turns out it was an unforseen issue with the vanilla/forge code. Everything should be working fine now. This should also fix #1 with the invisible lucky block spawns, however until I can get my hands on a copy of that mod in a nice way, I can't test.
