### ISSUE TITLE
Mobs cannot spawn dyed

### ISSUE THREAD

**Issue by airbreather** [Epoxide-MC/Colorful-Mobs#3]
As I mentioned in a [MCF post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2378875-colorful-mobs-now-with-20-more-colors?comment=48) a little while ago, mobs are not spawning dyed, no matter how high I tweak the rate.

I'm pretty sure that I have a [fix](https://github.com/airbreather/Colorful-Mobs/commit/47d05ff923164b8f2a53971d3186795583d47ed9) for this, but I can't get the colors to "stick" even on 409ff21 (with some out-of-band changes to build.gradle to get it to build on my machine), so I can't be confident enough in that change to submit a pull request for it.

**Comment by Darkhax** [comment]
Thank you for looking into this issue. I have noticed it myself, however I have found some wild mobs with the color on them which tells me it does work to an extent. I am currently in the process of rewriting the entire mod from the ground up to clean a lot of the networking up. As for the initialized variable, that was used to track if a mob has spawned before or not. This prevents mobs from having a chance to dye every time you reload the world. I will try to re-confirm this issue after my rewrite.

**Comment by airbreather** [comment]
What I'm seeing, with what I can get building, is that mobs can get colors (only manually applying the colors, not through the "randomly spawn as dyed" logic -- setting the chance to 1 should make all mobs get dyed; instead, none do), but they don't keep them between a world save / load cycle.  Maybe this was just unfortunate timing on my part, and 409ff21 is in a "transitional" state and isn't supposed to work right now.

The flaw with "initialized" is that, from my understanding at least, it can never be observed to be false, so it adds no actual information.  The way to do initialization that needs to happen once and only once per entity appears to be to put that logic in the `void init(Entity entity, World world)` method on `IExtendedEntityProperties`.
